/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Тудушлёп API
 * OpenAPI spec version: 0.1
 */
import type {
  BodyLoadUserImageUsersMediaPost,
  GetUserXpUsersUserIdXpGetParams,
} from '../api.schemas';
import { axiosInstance } from '.././axios';
import type { BodyType } from '.././axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Whoami
 */
export const whoamiUsersWhoamiGet = (
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/users/whoami`, method: 'GET' },
    options
  );
};
/**
 * @summary Get User
 */
export const getUserUsersUserIdGet = (
  userId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/users/${userId}`, method: 'GET' },
    options
  );
};
/**
 * @summary Get User Xp
 */
export const getUserXpUsersUserIdXpGet = (
  userId: number,
  params?: GetUserXpUsersUserIdXpGetParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/users/${userId}/xp`, method: 'GET', params },
    options
  );
};
/**
 * @summary Get User Image
 */
export const getUserImageUsersMediaUserIdGet = (
  userId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/users/media/${userId}`, method: 'GET' },
    options
  );
};
/**
 * @summary Load User Image
 */
export const loadUserImageUsersMediaPost = (
  bodyLoadUserImageUsersMediaPost: BodyType<BodyLoadUserImageUsersMediaPost>,
  options?: SecondParameter<typeof axiosInstance>
) => {
  const formData = new FormData();
  formData.append('image', bodyLoadUserImageUsersMediaPost.image);

  return axiosInstance<unknown>(
    {
      url: `/users/media`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options
  );
};
/**
 * @summary Remove User Image
 */
export const removeUserImageUsersMediaDelete = (
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/users/media`, method: 'DELETE' },
    options
  );
};
export type WhoamiUsersWhoamiGetResult = NonNullable<
  Awaited<ReturnType<typeof whoamiUsersWhoamiGet>>
>;
export type GetUserUsersUserIdGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserUsersUserIdGet>>
>;
export type GetUserXpUsersUserIdXpGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserXpUsersUserIdXpGet>>
>;
export type GetUserImageUsersMediaUserIdGetResult = NonNullable<
  Awaited<ReturnType<typeof getUserImageUsersMediaUserIdGet>>
>;
export type LoadUserImageUsersMediaPostResult = NonNullable<
  Awaited<ReturnType<typeof loadUserImageUsersMediaPost>>
>;
export type RemoveUserImageUsersMediaDeleteResult = NonNullable<
  Awaited<ReturnType<typeof removeUserImageUsersMediaDelete>>
>;
