/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Тудушлёп API
 * OpenAPI spec version: 0.1
 */
export type GetTeamMembersTeamsTeamIdMembersGetParams = {
  page: number;
  limit: number;
};

export type JoinTeamTeamsJoinGetParams = {
  link: string;
};

export type GetTeamTasksTeamsTeamIdTasksGetParams = {
  page: number;
  limit?: number;
  status?: TaskStatus;
  importance?: TaskImportance;
  attendant_id?: number;
};

export type EditTeamTeamsTeamIdPutParams = {
  title: string;
};

export type CreateTeamTeamsPostParams = {
  title: string;
};

export type ImportDataTasksImportPostParams = {
  team_id?: number;
};

export type ExportDataTasksExportGetParams = {
  team_id?: number;
};

export type GetPersonalTasksTasksGetParams = {
  page: number;
  limit?: number;
  status?: TaskStatus;
  importance?: TaskImportance;
};

export type CreateTaskTasksCreateTaskPostParams = {
  team_id?: number;
};

export type GetUserXpUsersUserIdXpGetParams = {
  team_id?: number;
};

export type ResetPasswordAuthResetPasswordPostParams = {
  password: string;
  repeat_password: string;
};

export interface HTTPRegisterValidationError {
  detail: string;
}

export interface AuthResponse {
  access_token: string;
  token_type: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskStatus = {
  planning: 'planning',
  running: 'running',
  done: 'done',
  cancelled: 'cancelled',
} as const;

export type TaskImportance =
  (typeof TaskImportance)[keyof typeof TaskImportance];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskImportance = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;

export type EditTaskTasksTaskIdPutParams = {
  title?: string | null;
  description?: string | null;
  task_status?: TaskStatus | null;
  task_importance?: TaskImportance | null;
  reminder?: string | null;
  attendant_id?: number | null;
  xp?: number | null;
};

export type TaskFormXp = number | null;

export type TaskFormTitle = string | null;

export type TaskFormTaskStatus = TaskStatus | null;

export type TaskFormTaskImportance = TaskImportance | null;

export type TaskFormReminder = string | null;

export type TaskFormDescription = string | null;

export type TaskFormAttendantId = number | null;

export interface TaskForm {
  attendant_id?: TaskFormAttendantId;
  description?: TaskFormDescription;
  reminder?: TaskFormReminder;
  task_importance?: TaskFormTaskImportance;
  task_status?: TaskFormTaskStatus;
  title: TaskFormTitle;
  xp?: TaskFormXp;
}

export interface RegisterForm {
  email: string;
  /** @minLength 8 */
  password: string;
  repeat_password: string;
  username: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type BodyLoginAuthLoginPostGrantType = string | null;

export type BodyLoginAuthLoginPostClientSecret = string | null;

export type BodyLoginAuthLoginPostClientId = string | null;

export interface BodyLoginAuthLoginPost {
  client_id?: BodyLoginAuthLoginPostClientId;
  client_secret?: BodyLoginAuthLoginPostClientSecret;
  grant_type?: BodyLoginAuthLoginPostGrantType;
  password: string;
  scope?: string;
  username: string;
}

export interface BodyLoadUserImageUsersMediaPost {
  image: Blob;
}

export interface BodyImportDataTasksImportPost {
  data: Blob;
}
