/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Тудушлёп API
 * OpenAPI spec version: 0.1
 */
import type {
  AuthResponse,
  BodyLoginAuthLoginPost,
  RegisterForm,
  ResetPasswordAuthResetPasswordPostParams,
} from '../api.schemas';
import { axiosInstance } from '.././axios';
import type { BodyType } from '.././axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Login
 */
export const loginAuthLoginPost = (
  bodyLoginAuthLoginPost: BodyType<BodyLoginAuthLoginPost>,
  options?: SecondParameter<typeof axiosInstance>
) => {
  const formUrlEncoded = new URLSearchParams();
  if (bodyLoginAuthLoginPost.grant_type !== undefined) {
    formUrlEncoded.append('grant_type', bodyLoginAuthLoginPost.grant_type);
  }
  formUrlEncoded.append('username', bodyLoginAuthLoginPost.username);
  formUrlEncoded.append('password', bodyLoginAuthLoginPost.password);
  if (bodyLoginAuthLoginPost.scope !== undefined) {
    formUrlEncoded.append('scope', bodyLoginAuthLoginPost.scope);
  }
  if (bodyLoginAuthLoginPost.client_id !== undefined) {
    formUrlEncoded.append('client_id', bodyLoginAuthLoginPost.client_id);
  }
  if (bodyLoginAuthLoginPost.client_secret !== undefined) {
    formUrlEncoded.append(
      'client_secret',
      bodyLoginAuthLoginPost.client_secret
    );
  }

  return axiosInstance<AuthResponse>(
    {
      url: `/auth/login`,
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      data: formUrlEncoded,
    },
    options
  );
};
/**
 * @summary Update Token
 */
export const updateTokenAuthUpdateTokenPost = (
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<AuthResponse>(
    { url: `/auth/update_token`, method: 'POST' },
    options
  );
};
/**
 * @summary Register
 */
export const registerAuthRegisterPost = (
  registerForm: BodyType<RegisterForm>,
  options?: SecondParameter<typeof axiosInstance>
) => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append('email', registerForm.email);
  formUrlEncoded.append('username', registerForm.username);
  formUrlEncoded.append('password', registerForm.password);
  formUrlEncoded.append('repeat_password', registerForm.repeat_password);

  return axiosInstance<unknown>(
    {
      url: `/auth/register`,
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      data: formUrlEncoded,
    },
    options
  );
};
/**
 * @summary Reset Password
 */
export const resetPasswordAuthResetPasswordPost = (
  params: ResetPasswordAuthResetPasswordPostParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/auth/reset-password`, method: 'POST', params },
    options
  );
};
export type LoginAuthLoginPostResult = NonNullable<
  Awaited<ReturnType<typeof loginAuthLoginPost>>
>;
export type UpdateTokenAuthUpdateTokenPostResult = NonNullable<
  Awaited<ReturnType<typeof updateTokenAuthUpdateTokenPost>>
>;
export type RegisterAuthRegisterPostResult = NonNullable<
  Awaited<ReturnType<typeof registerAuthRegisterPost>>
>;
export type ResetPasswordAuthResetPasswordPostResult = NonNullable<
  Awaited<ReturnType<typeof resetPasswordAuthResetPasswordPost>>
>;
