/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Тудушлёп API
 * OpenAPI spec version: 0.1
 */
import type {
  BodyImportDataTasksImportPost,
  CreateTaskTasksCreateTaskPostParams,
  EditTaskTasksTaskIdPutParams,
  ExportDataTasksExportGetParams,
  GetPersonalTasksTasksGetParams,
  ImportDataTasksImportPostParams,
  TaskForm,
} from '../api.schemas';
import { axiosInstance } from '.././axios';
import type { BodyType } from '.././axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Index
 */
export const indexTasksIndexGet = (
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks/index`, method: 'GET' },
    options
  );
};
/**
 * @summary Groups
 */
export const groupsTasksGroupsGet = (
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks/groups`, method: 'GET' },
    options
  );
};
/**
 * @summary Get Task
 */
export const getTaskTasksTaskIdGet = (
  taskId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks/${taskId}`, method: 'GET' },
    options
  );
};
/**
 * @summary Edit Task
 */
export const editTaskTasksTaskIdPut = (
  taskId: number,
  params?: EditTaskTasksTaskIdPutParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks/${taskId}`, method: 'PUT', params },
    options
  );
};
/**
 * @summary Delete Task
 */
export const deleteTaskTasksTaskIdDelete = (
  taskId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks/${taskId}`, method: 'DELETE' },
    options
  );
};
/**
 * @summary Create Task
 */
export const createTaskTasksCreateTaskPost = (
  taskForm: BodyType<TaskForm>,
  params?: CreateTaskTasksCreateTaskPostParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append('title', taskForm.title);
  if (taskForm.description !== undefined) {
    formUrlEncoded.append('description', taskForm.description);
  }
  if (taskForm.task_status !== undefined) {
    formUrlEncoded.append('task_status', taskForm.task_status);
  }
  if (taskForm.task_importance !== undefined) {
    formUrlEncoded.append('task_importance', taskForm.task_importance);
  }
  if (taskForm.reminder !== undefined) {
    formUrlEncoded.append('reminder', taskForm.reminder);
  }
  if (taskForm.attendant_id !== undefined) {
    formUrlEncoded.append('attendant_id', taskForm.attendant_id);
  }
  if (taskForm.xp !== undefined) {
    formUrlEncoded.append('xp', taskForm.xp);
  }

  return axiosInstance<unknown>(
    {
      url: `/tasks/create_task`,
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      data: formUrlEncoded,
      params,
    },
    options
  );
};
/**
 * @summary Get Personal Tasks
 */
export const getPersonalTasksTasksGet = (
  params: GetPersonalTasksTasksGetParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks`, method: 'GET', params },
    options
  );
};
/**
 * @summary Export Data
 */
export const exportDataTasksExportGet = (
  params?: ExportDataTasksExportGetParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/tasks/export`, method: 'GET', params },
    options
  );
};
/**
 * @summary Import Data
 */
export const importDataTasksImportPost = (
  bodyImportDataTasksImportPost: BodyType<BodyImportDataTasksImportPost>,
  params?: ImportDataTasksImportPostParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  const formData = new FormData();
  formData.append('data', bodyImportDataTasksImportPost.data);

  return axiosInstance<unknown>(
    {
      url: `/tasks/import`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      params,
    },
    options
  );
};
export type IndexTasksIndexGetResult = NonNullable<
  Awaited<ReturnType<typeof indexTasksIndexGet>>
>;
export type GroupsTasksGroupsGetResult = NonNullable<
  Awaited<ReturnType<typeof groupsTasksGroupsGet>>
>;
export type GetTaskTasksTaskIdGetResult = NonNullable<
  Awaited<ReturnType<typeof getTaskTasksTaskIdGet>>
>;
export type EditTaskTasksTaskIdPutResult = NonNullable<
  Awaited<ReturnType<typeof editTaskTasksTaskIdPut>>
>;
export type DeleteTaskTasksTaskIdDeleteResult = NonNullable<
  Awaited<ReturnType<typeof deleteTaskTasksTaskIdDelete>>
>;
export type CreateTaskTasksCreateTaskPostResult = NonNullable<
  Awaited<ReturnType<typeof createTaskTasksCreateTaskPost>>
>;
export type GetPersonalTasksTasksGetResult = NonNullable<
  Awaited<ReturnType<typeof getPersonalTasksTasksGet>>
>;
export type ExportDataTasksExportGetResult = NonNullable<
  Awaited<ReturnType<typeof exportDataTasksExportGet>>
>;
export type ImportDataTasksImportPostResult = NonNullable<
  Awaited<ReturnType<typeof importDataTasksImportPost>>
>;
