/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Тудушлёп API
 * OpenAPI spec version: 0.1
 */
import type {
  CreateTeamTeamsPostParams,
  EditTeamTeamsTeamIdPutParams,
  GetTeamMembersTeamsTeamIdMembersGetParams,
  GetTeamTasksTeamsTeamIdTasksGetParams,
  JoinTeamTeamsJoinGetParams,
} from '../api.schemas';
import { axiosInstance } from '.././axios';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Create Team
 */
export const createTeamTeamsPost = (
  params: CreateTeamTeamsPostParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/`, method: 'POST', params },
    options
  );
};
/**
 * @summary Get Mine Teams
 */
export const getMineTeamsTeamsGet = (
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>({ url: `/teams/`, method: 'GET' }, options);
};
/**
 * @summary Edit Team
 */
export const editTeamTeamsTeamIdPut = (
  teamId: number,
  params: EditTeamTeamsTeamIdPutParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}`, method: 'PUT', params },
    options
  );
};
/**
 * @summary Get Team Tasks
 */
export const getTeamTasksTeamsTeamIdTasksGet = (
  teamId: number,
  params: GetTeamTasksTeamsTeamIdTasksGetParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}/tasks`, method: 'GET', params },
    options
  );
};
/**
 * @summary Create Invite Link
 */
export const createInviteLinkTeamsInviteLinkTeamIdGet = (
  teamId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/invite-link/${teamId}`, method: 'GET' },
    options
  );
};
/**
 * @summary Join Team
 */
export const joinTeamTeamsJoinGet = (
  params: JoinTeamTeamsJoinGetParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/join`, method: 'GET', params },
    options
  );
};
/**
 * @summary Get Team Members
 */
export const getTeamMembersTeamsTeamIdMembersGet = (
  teamId: number,
  params: GetTeamMembersTeamsTeamIdMembersGetParams,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}/members`, method: 'GET', params },
    options
  );
};
/**
 * @summary Kick User
 */
export const kickUserTeamsTeamIdKickUserIdPost = (
  teamId: number,
  userId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}/kick/${userId}`, method: 'POST' },
    options
  );
};
/**
 * @summary Make Admin
 */
export const makeAdminTeamsTeamIdMakeAdminUserIdPost = (
  teamId: number,
  userId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}/make-admin/${userId}`, method: 'POST' },
    options
  );
};
/**
 * @summary Make Member
 */
export const makeMemberTeamsTeamIdMakeMemberUserIdPost = (
  teamId: number,
  userId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}/make-member/${userId}`, method: 'POST' },
    options
  );
};
/**
 * @summary Make Owner
 */
export const makeOwnerTeamsTeamIdMakeOwnerUserIdPost = (
  teamId: number,
  userId: number,
  options?: SecondParameter<typeof axiosInstance>
) => {
  return axiosInstance<unknown>(
    { url: `/teams/${teamId}/make-owner/${userId}`, method: 'POST' },
    options
  );
};
export type CreateTeamTeamsPostResult = NonNullable<
  Awaited<ReturnType<typeof createTeamTeamsPost>>
>;
export type GetMineTeamsTeamsGetResult = NonNullable<
  Awaited<ReturnType<typeof getMineTeamsTeamsGet>>
>;
export type EditTeamTeamsTeamIdPutResult = NonNullable<
  Awaited<ReturnType<typeof editTeamTeamsTeamIdPut>>
>;
export type GetTeamTasksTeamsTeamIdTasksGetResult = NonNullable<
  Awaited<ReturnType<typeof getTeamTasksTeamsTeamIdTasksGet>>
>;
export type CreateInviteLinkTeamsInviteLinkTeamIdGetResult = NonNullable<
  Awaited<ReturnType<typeof createInviteLinkTeamsInviteLinkTeamIdGet>>
>;
export type JoinTeamTeamsJoinGetResult = NonNullable<
  Awaited<ReturnType<typeof joinTeamTeamsJoinGet>>
>;
export type GetTeamMembersTeamsTeamIdMembersGetResult = NonNullable<
  Awaited<ReturnType<typeof getTeamMembersTeamsTeamIdMembersGet>>
>;
export type KickUserTeamsTeamIdKickUserIdPostResult = NonNullable<
  Awaited<ReturnType<typeof kickUserTeamsTeamIdKickUserIdPost>>
>;
export type MakeAdminTeamsTeamIdMakeAdminUserIdPostResult = NonNullable<
  Awaited<ReturnType<typeof makeAdminTeamsTeamIdMakeAdminUserIdPost>>
>;
export type MakeMemberTeamsTeamIdMakeMemberUserIdPostResult = NonNullable<
  Awaited<ReturnType<typeof makeMemberTeamsTeamIdMakeMemberUserIdPost>>
>;
export type MakeOwnerTeamsTeamIdMakeOwnerUserIdPostResult = NonNullable<
  Awaited<ReturnType<typeof makeOwnerTeamsTeamIdMakeOwnerUserIdPost>>
>;
